# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Orange and Pink
email: jacqueline@ordrstudio.com
description: > # this means to ignore newlines until "baseurl:"
  Non-relevant blogs and probably really biased.
  Have a lot of cute stuffs though, atleast imho.
  Read with skeptical eyes. Thank!
baseurl: "OrangeNPink" # the subpath of your site, e.g. /blog
url: "http://ordrstudio.com" # the base hostname & protocol for your site

github_username:  ComposerCookie
gitlab_username: JackieCharmander
gplus_username:  Jacqueline Tran

timezone: America/New_York

# Build settings
markdown: kramdown
